/**
 * Created by nt on 12.04.2017.
 */
export const ACTION_TYPE_CHANGE_INITIALS = "CHANGE_INITIALS";
export const ACTION_TYPE_CHANGE_FIRSTNAME = "CHANGE_FIRSTNAME";
export const ACTION_TYPE_CHANGE_LASTNAME = "CHANGE_LASTNAME";
export const ACTION_TYPE_CHANGE_BIRTHDATE = "CHANGE_BIRTHDATE";

export const ACTION_REQUEST_CONSULTANTS = "REQUEST_CONSULTANTS";
export const ACTION_TYPE_RECEIVE_CONSULTANTS = "RECEIVE_CONSULTANTS";